source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-theme-minimal"
gem "webrick", "~> 1.7" # required to run Jekyll on Ruby >= 3.0
